# workflow name and on push do some jobs
name : Testing
on : push

# every workflow consist of some jobs
#jobs -> (What tasks should happen anytime i try to push to a repository)
# test_project is my job name
# actions/checkout@v2 -> github writes this code helps you checkout your code on a Virtual Machine which in this case is ubuntu a linux VM(able to access my code to be able to run it)

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django Unit Tests
      run:
        pip3 install --user django
        python manage.py test
        


